### ISSUE TITLE
Fix 15 currently broken tests

### ISSUE THREAD

**Issue by msoechting** [hpicgs/node#42]
Result of `make test-only` on the current node_lib branch returns 15 failed JS tests (see below). On the master branch of this fork, these tests run successfully.

The C++ tests all passed. 

```
=== release test-cli-syntax ===                                                
Path: parallel/test-cli-syntax
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'Embedded mode\n' === ''
    at /home/m/Desktop/node/test/parallel/test-cli-syntax.js:101:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/m/Desktop/node/test/parallel/test-cli-syntax.js:96:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-cli-syntax.js


=== release test-cwd-enoent-repl ===                                           
Path: parallel/test-cwd-enoent-repl
Embedded mode
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at Pipe.onread (net.js:619:25)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-cwd-enoent-repl.js


=== release test-force-repl ===                                                
Path: parallel/test-force-repl
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'Embedded mode\n' === '> '
    at Socket.<anonymous> (/home/m/Desktop/node/test/parallel/test-force-repl.js:13:10)
    at Socket.<anonymous> (/home/m/Desktop/node/test/common/index.js:522:15)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:248:13)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onread (net.js:598:20)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-force-repl.js


=== release test-force-repl-with-eval ===                   
Path: parallel/test-force-repl-with-eval
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at process.<anonymous> (/home/m/Desktop/node/test/parallel/test-force-repl-with-eval.js:22:3)
    at emitOne (events.js:130:20)
    at process.emit (events.js:221:7)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-force-repl-with-eval.js


=== release test-preload ===                                                   
Path: parallel/test-preload
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'A\nEmbedded mode\n' === 'A\n> '
    at ChildProcess.<anonymous> (/home/m/Desktop/node/test/parallel/test-preload.js:98:10)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-preload.js


=== release test-repl-harmony ===                                              
Path: parallel/test-repl-harmony
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at Socket.<anonymous> (/home/m/Desktop/node/test/parallel/test-repl-harmony.js:44:3)
    at emitNone (events.js:120:20)
    at Socket.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-repl-harmony.js


=== release test-repl-require-context ===                         
Path: parallel/test-repl-require-context
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: [ 'Embedded mode', '' ] deepStrictEqual [ 'undefined', 'true', 'true', '' ]
    at ChildProcess.child.on.common.mustCall (/home/m/Desktop/node/test/parallel/test-repl-require-context.js:18:10)
    at ChildProcess.<anonymous> (/home/m/Desktop/node/test/common/index.js:522:15)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-repl-require-context.js


=== release test-repl-sigint ===                                 
Path: parallel/test-repl-sigint
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at Pipe.onread (net.js:619:25)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-repl-sigint.js


=== release test-repl-sigint-nested-eval ===                        
Path: parallel/test-repl-sigint-nested-eval
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at Pipe.onread (net.js:619:25)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-repl-sigint-nested-eval.js


=== release test-repl-unexpected-token-recoverable ===                     
Path: parallel/test-repl-unexpected-token-recoverable
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at Socket.<anonymous> (/home/m/Desktop/node/test/parallel/test-repl-unexpected-token-recoverable.js:29:3)
    at emitNone (events.js:120:20)
    at Socket.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-repl-unexpected-token-recoverable.js


=== release test-stdin-script-child ===                                        
Path: parallel/test-stdin-script-child
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'Embedded mode\n' === '22740\n'
    at ChildProcess.<anonymous> (/home/m/Desktop/node/test/parallel/test-stdin-script-child.js:27:12)
    at ChildProcess.<anonymous> (/home/m/Desktop/node/test/common/index.js:522:15)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-stdin-script-child.js


=== release test-stdin-script-child-option ===                    
Path: parallel/test-stdin-script-child-option
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'Embedded mode' === '--option-to-be-seen-on-child'
    at Socket.child.stdout.on.common.mustCall (/home/m/Desktop/node/test/parallel/test-stdin-script-child-option.js:16:10)
    at Socket.<anonymous> (/home/m/Desktop/node/test/common/index.js:522:15)
    at emitNone (events.js:120:20)
    at Socket.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Command: out/Release/node /home/m/Desktop/node/test/parallel/test-stdin-script-child-option.js


=== release test-fs-readfile-tostring-fail ===                                 
Path: sequential/test-fs-readfile-tostring-fail
/home/m/Desktop/node/test/sequential/test-fs-readfile-tostring-fail.js:60
  throw err;
  ^

AssertionError [ERR_ASSERTION]: false == true
    at /home/m/Desktop/node/test/sequential/test-fs-readfile-tostring-fail.js:34:12
    at /home/m/Desktop/node/test/common/index.js:522:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
Command: out/Release/node /home/m/Desktop/node/test/sequential/test-fs-readfile-tostring-fail.js


=== release test-repl-timeout-throw ===                                        
Path: sequential/test-repl-timeout-throw
Embedded mode
var throws = 0;process.on("exit",function(){console.log(throws)});function thrower(){console.log("THROW",throws++);XXX};setTimeout(thrower);""
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at Pipe.onread (net.js:619:25)
Command: out/Release/node /home/m/Desktop/node/test/sequential/test-repl-timeout-throw.js
```

**Comment by cmfcmf** [comment]
This is most likely because of #34.

**Comment by cmfcmf** [comment]
Using the `dev` branch, only a single test is failing for me.
```
[ RUN      ] InspectorSocketServerTest.ServerCannotStart
../test/cctest/test_inspector_socket_server.cc:523: Failure
Value of: server2->Start()
  Actual: true
Expected: false
[--I] signal   0x6b2648
[-AI] async    0x6b2490
[RA-] tcp      0x17244f0
[RA-] tcp      0x1724650
../test/cctest/test_inspector_socket_server.cc:83: Failure
Value of: err
  Actual: -16
Expected: 0
[  FAILED  ] InspectorSocketServerTest.ServerCannotStart (14 ms)
```

**Comment by msoechting** [comment]
I built the cctest on new-dev (Tims attempt) yesterday and they all passed.

**Comment by cmfcmf** [comment]
I should've mentioned that this is the test that always failed for me. I suppose all your test would also be green on the `dev` branch.
